### ISSUE TITLE
json-ptr vulnerability

### ISSUE THREAD

**Issue by kumarpv12** [exegesis-js/exegesis-express#53]
Hi Team,
Json-ptr@2.2.0 is a indirect dependency for exegesis-express and this version has vulnerabilities.  Dependency is exegesis-express -> exegesis@3.0.1 -> json-ptr@2.2.0. Can you please change the exegesis dependency version from 3.0.1 to 4.1.0.?

https://snyk.io/test/npm/exegesis-express/3.0.0

**Comment by jwalton** [comment]
Thanks for pointing this out!
